In [3]:
import numpy as np
helpful to play or create numbers

In [4]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
### lasts will be not included
np.arange(1,100) 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [19]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((2,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [28]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [29]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(3,5)

array([[0.29664904, 0.02675477, 0.9342255 , 0.3352978 , 0.36567082],
       [0.50835386, 0.77114918, 0.24283599, 0.84384279, 0.12115521],
       [0.65866755, 0.83283803, 0.9414005 , 0.93491254, 0.58195381]])

In [23]:
arr=np.random.randn(2,4)
arr

array([[ 0.16553268, -0.09150096,  0.73588924,  0.15096988],
       [ 1.18578458,  0.71453606, -0.68212737, -1.58988244]])

In [30]:
np.random.randint(2,100)

38

In [31]:
np.random.randint(20,56,100)

array([28, 39, 26, 24, 33, 25, 39, 42, 34, 34, 48, 25, 37, 42, 29, 35, 30,
       50, 45, 41, 53, 42, 20, 35, 50, 54, 38, 34, 46, 54, 48, 42, 38, 34,
       34, 36, 27, 34, 50, 45, 51, 21, 35, 43, 42, 46, 50, 27, 34, 48, 44,
       26, 51, 24, 36, 27, 26, 52, 38, 49, 41, 33, 31, 50, 30, 29, 29, 43,
       30, 53, 23, 50, 31, 51, 23, 42, 31, 52, 31, 21, 28, 26, 45, 29, 30,
       36, 39, 26, 38, 50, 45, 44, 51, 46, 33, 55, 53, 39, 53, 55])

In [24]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
rand_array=np.random.randint(0,100,20)
rand_array

array([ 7, 34, 85, 33, 24, 22, 27,  5, 70,  1, 43, 65, 88, 99, 44, 31, 85,
        9,  7, 97])

In [32]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
sample_array.reshape(2,3)

ValueError: cannot reshape array of size 30 into shape (2,3)

In [36]:
rand_array.max()

99

In [37]:
rand_array.argmax()

13

In [38]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
a=np.random.rand(2,3)
a

array([[0.20370925, 0.84320596, 0.86339238],
       [0.56353381, 0.21785445, 0.57120296]])

In [41]:
a.T

array([[0.20370925, 0.56353381],
       [0.84320596, 0.21785445],
       [0.86339238, 0.57120296]])

In [44]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
sample_array[0]

10

In [46]:
sample_array[2:5]

array([12, 13, 14])

In [48]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [49]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [50]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [51]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [53]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [54]:
### two dimentional array
import numpy as np

In [55]:
sample_array=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_array

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [56]:
sample_array[1,2]

21

In [57]:
sample_array[2,:]

array([56, 76, 24,  7])

In [58]:
sample_array[2]

array([56, 76, 24,  7])

In [59]:
sample_array[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])