In [7]:
### selection techniques
import numpy as np

In [8]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [9]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [10]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [11]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [12]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [13]:
np.max(sample_array)

19

In [14]:
np.min(sample_array)

1

In [16]:
np.argmax(sample_array)

18

In [17]:
np.argmin(sample_array)

0

In [18]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [19]:
np.var(sample_array)

30.0

In [20]:
np.std(sample_array)

5.477225575051661

In [21]:
np.mean(sample_array)

10.0

In [22]:
array=np.random.randn(3,4)
array

array([[ 0.40526456, -0.2757544 , -0.75567429,  1.68258564],
       [ 0.21833066,  0.49102137,  0.60957757,  1.23334154],
       [-1.24791973,  0.20329307,  0.76407167,  0.97085866]])

In [23]:
np.round(array,decimals=2)

array([[ 0.41, -0.28, -0.76,  1.68],
       [ 0.22,  0.49,  0.61,  1.23],
       [-1.25,  0.2 ,  0.76,  0.97]])

In [28]:
sports=np.array['golf','cricket','fball','cricket']
np.unique(sports)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [29]:
###pandas library dataframs and indexing
import pandas as pd
import numpy as np

In [31]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [32]:
sports1['football']

2

In [33]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','basketball','golf'])
sports2

cricket       11
football       2
basketball     3
golf           4
dtype: int64

In [34]:
sports1+sports2

cricket       12
football       4
basketball     6
golf           8
dtype: int64

In [35]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.625326  0.620523  0.738447  0.090782  0.600153
B  0.865046  0.190432  0.964792  0.558315  0.988166
C  0.258245  0.517299  0.674221  0.075646  0.567583
D  0.817141  0.710769  0.877300  0.824116  0.275409
E  0.827498  0.220833  0.510427  0.539385  0.821888
F  0.311597  0.643543  0.470035  0.172174  0.232200
G  0.231446  0.325612  0.304414  0.490174  0.407541
H  0.648869  0.648322  0.440451  0.193269  0.110207

In [36]:
df1["score1"]

A    0.625326
B    0.865046
C    0.258245
D    0.817141
E    0.827498
F    0.311597
G    0.231446
H    0.648869
Name: score1, dtype: float64

In [38]:
df1[["score1","score2","score3"]]

score1    score2    score3
A  0.625326  0.620523  0.738447
B  0.865046  0.190432  0.964792
C  0.258245  0.517299  0.674221
D  0.817141  0.710769  0.877300
E  0.827498  0.220833  0.510427
F  0.311597  0.643543  0.470035
G  0.231446  0.325612  0.304414
H  0.648869  0.648322  0.440451

In [41]:
df1['score6']=df1['score2']+df1['score3']
df1

score1    score2    score3    score4    score5    score6
A  0.625326  0.620523  0.738447  0.090782  0.600153  1.358970
B  0.865046  0.190432  0.964792  0.558315  0.988166  1.155223
C  0.258245  0.517299  0.674221  0.075646  0.567583  1.191520
D  0.817141  0.710769  0.877300  0.824116  0.275409  1.588069
E  0.827498  0.220833  0.510427  0.539385  0.821888  0.731260
F  0.311597  0.643543  0.470035  0.172174  0.232200  1.113578
G  0.231446  0.325612  0.304414  0.490174  0.407541  0.630026
H  0.648869  0.648322  0.440451  0.193269  0.110207  1.088773

In [43]:
df2={'ID':['101','102','103','107','176'],'name':['jhon','mercy','akash','kavin','lally'],'profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   name  profit
0  101   jhon      20
1  102  mercy      54
2  103  akash      56
3  107  kavin      87
4  176  lally     123

In [44]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [45]:
df[["ID","name","profit"]]

ID   name  profit
0  101   jhon      20
1  102  mercy      54
2  103  akash      56
3  107  kavin      87
4  176  lally     123

In [48]:

df=df.drop("ID",axis=1)
df
df.drop(3)

KeyError: "['ID'] not found in axis"

In [49]:
df

name  profit
0   jhon      20
1  mercy      54
2  akash      56
3  kavin      87
4  lally     123

In [50]:
df.drop(3)

name  profit
0   jhon      20
1  mercy      54
2  akash      56
4  lally     123